name: esewa_pnp
description: Integrate native eSewa payment method in your flutter application with ease.
version: 2.0.1
homepage: https://github.com/ayyshim/esewa_pnp/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: np.com.uashim.esewa_pnp
        pluginClass: EsewaPnpPlugin
      ios:
        pluginClass: EsewaPnpPlugin
